.PHONY: clean All

All:
	@echo "----------Building project:[ 04-Section4-Getting-Started - Debug ]----------"
	@cd "04-Section4-Getting-Started" && "$(MAKE)" -f  "04-Section4-Getting-Started.mk"
clean:
	@echo "----------Cleaning project:[ 04-Section4-Getting-Started - Debug ]----------"
	@cd "04-Section4-Getting-Started" && "$(MAKE)" -f  "04-Section4-Getting-Started.mk" clean
