.PHONY: clean All

All:
	@echo "----------Building project:[ 09-Challenge - Debug ]----------"
	@cd "09-Challenge" && "$(MAKE)" -f  "09-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ 09-Challenge - Debug ]----------"
	@cd "09-Challenge" && "$(MAKE)" -f  "09-Challenge.mk" clean
