.PHONY: clean All

All:
	@echo "----------Building project:[ 01-SimplePointers - Debug ]----------"
	@cd "01-SimplePointers" && "$(MAKE)" -f  "01-SimplePointers.mk"
clean:
	@echo "----------Cleaning project:[ 01-SimplePointers - Debug ]----------"
	@cd "01-SimplePointers" && "$(MAKE)" -f  "01-SimplePointers.mk" clean
