.PHONY: clean All

All:
	@echo "----------Building project:[ 12-Looping-NestedLoops - Debug ]----------"
	@cd "12-Looping-NestedLoops" && "$(MAKE)" -f  "12-Looping-NestedLoops.mk"
clean:
	@echo "----------Cleaning project:[ 12-Looping-NestedLoops - Debug ]----------"
	@cd "12-Looping-NestedLoops" && "$(MAKE)" -f  "12-Looping-NestedLoops.mk" clean
