.PHONY: clean All

All:
	@echo "----------Building project:[ 01-CharFunctions - Debug ]----------"
	@cd "01-CharFunctions" && "$(MAKE)" -f  "01-CharFunctions.mk"
clean:
	@echo "----------Cleaning project:[ 01-CharFunctions - Debug ]----------"
	@cd "01-CharFunctions" && "$(MAKE)" -f  "01-CharFunctions.mk" clean
